#!/usr/bin/bash
find ./src/ -type f ! -name "*.c" -exec rm {} \;

if [[ $# -eq 0 ]]; then
    echo -e "Usage: ./ggcr <filename>\n"
else
    filename=$1
    cd src
    gcc ${filename}.c -o $filename -lm
    chmod +x $filename
    ./$filename
fi 
